### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by chovy** [boramalper/magnetico#232]
```
$ docker-compose up --build
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.magneticod.build contains unsupported option: 'image'
services.magneticow.build contains unsupported option: 'image'
```

**Comment by alcalyn** [comment]
Yes I have the same issue, you have to move `image:` outside of `build:`

Here is a working `docker-compose.yml`:

``` yml
version: "2"

services:
  magneticod:
    image: boramalper/magneticod
    build:
      context: .
      dockerfile: Dockerfile.magneticod
    [...]

  magneticow:
    image: boramalper/magneticow
    build:
      context: .
      dockerfile: Dockerfile.magneticow
    [...]
```

This one will build image from source because `build:` takes precedence over `image:`.

If you want to use already built image from docker hub, just comment out `build:` in bith services:

``` yml
version: "2"

services:
  magneticod:
    image: boramalper/magneticod
#    build:
#      context: .
#      dockerfile: Dockerfile.magneticod
    volumes:
      - magneticod-data:/root/.local/share/magneticod
      - magneticod-config:/root/.config/magneticod

  magneticow:
    image: boramalper/magneticow
#    build:
#      context: .
#      dockerfile: Dockerfile.magneticow
    volumes:
      - magneticod-data:/root/.local/share/magneticod
    depends_on:
      # It doesn't necessarily "depend" on magneticod, but you would probably like to start them at the same time.
      - magneticod
    ports:
      - "8080:8080"

volumes:
  magneticod-config:

  magneticod-data:
```

:warning: Warning, at this time, docker hub images have been built two month ago, so it may worth build your own image from source (i.e **not** commenting out `build:` sections).
